---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(p8105.datasets)
library(shiny)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>%
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>%
  filter(!is.na(stars))
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs = nyc_airbnb %>% distinct(borough)

selectInput(
  inputId = "borough_choice", #id to refer to
  label = h3("Borough Choice"), #what user sees, h3 means header size 3
  choices = boroughs, #choices
  selected = "Manhattan"
)

sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min = 50, max = 1000, value = c(100, 250)
)

room_types = nyc_airbnb %>% distinct(room_type) %>% pull()

radioButtons(
  inputId = "room_choice",
  label = h3("Room Type"),
  choices = room_types,
  selected = "Entire home/apt"
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>%
  filter(borough == input[["borough_choice"]],
         price >= input[["price_range"]][1],
         price <= input[["price_range"]][2],
         room_type == input[["room_choice"]]) %>%
  plot_ly(x = ~lat, y = ~long, color = ~price, type = "scatter", mode = "markers", alpha = .5)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>% 
    filter(
      borough == input[["borough_choice"]], 
      price %in% input[["price_range"]][1]:input[["price_range"]][2],
      room_type == input[["room_choice"]]) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})
```

### Chart C

```{r}
renderPrint({
  input[["room_choice"]]
})
```

